/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/B2YC0OXd7bE
 */
import { CardContent, CardFooter, Card } from "@/components/ui/card"
import Link from "next/link"
import Image from "next/image"

export default function About() {
  return (
    <section className="w-full py-10 bg-white" style={{ backgroundRepeat: 'no-repeat', backgroundSize: 'cover' }}>

      <div className="max-w-3xl mx-auto px-4">
        <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl text-center">About</h2>
        <p className="mt-4 text-center text-gray-500 md:text-xl">
          This personal project was made to provide a safe place to search for LGBTQ+ books. 
          Made with love by
        </p>

        <div className="mt-10 flex flex-col items-center">
          <Image
            alt="Avatar"
            className="rounded-full"
            height={96}
            src="/witch@udio.png"
            width={96}
          />
          <h3 className="mt-4 text-lg font-semibold">witch@udio</h3>
        </div>

        <div className="mt-6 flex justify-center">
          <Link href="https://twitter.com/witchaudio_" className="p-2">
            <TwitterIcon className="w-4 h-4 text-gray-500 hover:text-gray-700" />
          </Link>
          <Link href="https://github.com/witchaudio" className="p-2">
            <GithubIcon className="w-4 h-4 text-gray-500 hover:text-gray-700" />
          </Link>
        </div>
      </div>
    </section>
  );
}



function TwitterIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}


function LinkedinIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function GithubIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  )
}
